version: 2.1

executors:
  docker:
    working_directory: /tmp/workspace
    docker:
      - image: docker:latest

jobs:
    docker:
        parameters:
            with_deploy:
                type: boolean
                default: false
        executor: docker
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.09.0-ce
            - run:
                name: Build
                command: |
                    docker build .
            - when:
                condition: <<parameters.with_deploy>>
                steps:
                    - run:
                        name: Publish
                        command: |
                            echo "Unimplemented!"
                            exit 1
                            
workflows:
    version: 2
    build:
        jobs:
            - docker:
                name: auto-build
                with_deploy: false
                filters:
                    branches:
                        only: master